export const mapItems = [
    {
        id: 1,
        type: 'supply',
        material: 'Bata Merah Utuh',
        amount: '80 pcs',
        condition: 'Utuh',
        address: 'Jl. Pandanaran No. 42',
        distance: '0.8 km',
        lat: -6.9925,
        lng: 110.4205,
        match: 96,
        status: 'Siap Angkut',
        donor: 'Bpk. Hendra W.',
        image: '/images/material-bata.jpg',
        aiEstimate: 'Cocok untuk perbaikan saluran drainase RT 04'
    },
    {
        id: 2,
        type: 'demand',
        title: 'Perbaikan Gang & Trotoar RT 03 / RW 05',
        need: 'Semen + Pasir',
        amount: '8 sak + 2 kubik',
        currentAmount: '18 m²',
        targetAmount: '30 m²',
        address: 'Semarang Selatan',
        distance: '1.1 km',
        lat: -7.0055,
        lng: 110.4155,
        progress: 60,
        match: 94,
        priority: 'URGENT',
        image: '/images/perbaikan-gang.jpg',
        aiEstimate: 'Estimasi 3 Sak Semen & 2 Sak Pasir',
        description: 'Warga swadaya telah menyiapkan tenaga tukang. Menunggu redistribusi sisa semen proyek renovasi terdekat untuk pengecoran.',
        remaining: 'Kurang 12 m² Ubin / Keramik Lantai 40×40'
    },
    {
        id: 3,
        type: 'supply',
        material: 'Semen Portland Sisa',
        amount: '5 sak',
        condition: 'Kering & Utuh',
        address: 'Kec. Candisari',
        distance: '2.1 km',
        lat: -6.9855,
        lng: 110.4315,
        match: 91,
        status: 'Siap Angkut',
        image: '/images/material-semen.jpg',
        aiEstimate: 'Kondisi material 95% layak digunakan'
    },
    {
        id: 4,
        type: 'demand',
        title: 'Renovasi Kelas Bina Sial RW',
        need: 'Keramik 14×40',
        amount: '30 m²',
        address: 'Kec. Candisari',
        distance: '1.5 km',
        lat: -7.0005,
        lng: 110.4255,
        progress: 60,
        match: 89,
        priority: 'URGENT',
        image: '/images/renovasi-kelas.jpg',
        aiEstimate: 'Keramik paling sesuai untuk kebutuhan renovasi'
    },
    {
        id: 5,
        type: 'supply',
        material: 'Keramik',
        amount: '45 pcs',
        condition: 'Grade A',
        address: 'Jl. Ahmad Yani',
        distance: '2.8 km',
        lat: -6.9985,
        lng: 110.4385,
        match: 88,
        status: 'Terverifikasi',
        image: '/images/material-keramik.jpg',
        aiEstimate: 'Material sesuai dengan kebutuhan renovasi'
    }
];

export const materialFilters = ['Semua', 'Semen', 'Keramik', 'Bata', 'Kayu'];