# Generated by Django 6.1 on 2026-09-08 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='description',
            new_name='deskripsi',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='price',
            new_name='harga',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='seller',
            new_name='penjual',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='listing_type',
            new_name='type_penjualan',
        ),
    ]
