# Generated by Django 6.1 on 2026-09-11 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_description_material_deskripsi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='kategori',
        ),
        migrations.RemoveField(
            model_name='material',
            name='penjual',
        ),
        migrations.DeleteModel(
            name='Foto_Material',
        ),
        migrations.DeleteModel(
            name='Kategori',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
