# Generated by Django 6.1 on 2026-09-11 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0003_remove_material_kategori_remove_material_penjual_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_material', models.CharField(max_length=100)),
                ('kategori', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('kondisi_barang', models.CharField(choices=[('baru', 'baru'), ('layak', 'layak  pakai'), ('perbaikan', 'perlu perbaikan'), ('second', 'setengah pakai')], default='layak', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='donations/')),
                ('alamat', models.TextField()),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('catatan', models.TextField(default='Silahkan Ambill di Lokasi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
