# Generated by Django 6.1 on 2026-09-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialform',
            name='nama_pemilik',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materialform',
            name='no_hp',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materialform',
            name='kategori',
            field=models.CharField(choices=[('material', 'material'), ('batu', 'baru'), ('dll', 'dan lain lain')], max_length=100),
        ),
    ]
