# Generated by Django 6.1 on 2026-09-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_materialform_nama_pemilik_materialform_no_hp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialform',
            name='no_hp',
            field=models.CharField(max_length=50),
        ),
    ]
