# Generated by Django 6.1 on 2026-09-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_materialform_no_hp'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialform',
            name='tersedia',
            field=models.BooleanField(default=True),
        ),
    ]
