# Generated by Django 6.1 on 2026-09-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_materialform_tersedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialform',
            name='bobot',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
    ]
