# Generated by Django 6.1 on 2026-09-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_materialform_bobot'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialform',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
