# Generated by Django 6.1 on 2026-09-13 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0006_alter_materialform_no_hp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Klaim_Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_penerima', models.CharField(max_length=100)),
                ('alamat_penerima', models.CharField(max_length=100)),
                ('no_hp', models.IntegerField()),
                ('catatan', models.TextField()),
                ('lat_penerima', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude_penerima', models.DecimalField(decimal_places=6, max_digits=9)),
                ('jarak_km', models.FloatField(default=0.0)),
                ('biaya_ongkir', models.IntegerField(default=0)),
                ('tanggal_klaim', models.DateTimeField(auto_now_add=True)),
                ('material_diambil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.materialform')),
                ('penerima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
