# Generated by Django 6.1 on 2026-09-13 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penerima', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='klaim_barang',
            old_name='material_diambil',
            new_name='material',
        ),
    ]
